#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:-"amd64"}
SUFFIX="-${ARCH}"

cd $(dirname $0)/..

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-ibuildthecloud}

if echo $TAG | grep -q dirty; then
    TAG=dev
fi

mkdir -p dist/artifacts
cp bin/* dist/artifacts/

IMAGE=${REPO}/skeltest:${TAG}
docker build -f package/Dockerfile -t ${IMAGE} .
echo Built ${IMAGE}
